name: Sinatra App CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sinatra-app:latest

      - name: Deploy with zero downtime (example via SSH)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/sinatra-app:latest
            docker stop sinatra-green || true
            docker rename sinatra-blue sinatra-old || true
            docker run -d --name sinatra-blue -p 80:4567 ${{ secrets.DOCKER_USERNAME }}/sinatra-app:latest
            sleep 10
            docker stop sinatra-old || true
            docker rm sinatra-old || true
